version: '3.8'

services:
  ethereum-node:
    image: ethereum/client-go:v1.11.6
    container_name: ethereum-local
    command:
      - --datadir=/root/.ethereum
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.corsdomain=*
      - --http.api=eth,net,web3,personal,miner,admin,debug,txpool
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.origins=*
      - --ws.api=eth,net,web3,personal,miner,admin,debug,txpool
      - --networkid=1337
      - --mine
      - --miner.threads=1
      - --miner.gasprice=0
      - --miner.etherbase=0xad09fef381c61777d5d929a5a77c40ad8081cd69
      - --unlock=0xad09fef381c61777d5d929a5a77c40ad8081cd69
      - --password=/root/.ethereum/password.txt
      - --allow-insecure-unlock
      - --rpc.allow-unprotected-txs
      - --nodiscover
      - --maxpeers=0
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - ./data:/root/.ethereum
      - ./genesis.json:/root/genesis.json
    healthcheck:
      test: ["CMD", "geth", "attach", "--exec", "eth.blockNumber", "/root/.ethereum/geth.ipc"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  block-explorer:
    image: alethio/ethereum-lite-explorer
    container_name: ethereum-explorer
    ports:
      - "8080:80"
    environment:
      - APP_NODE_URL=http://localhost:8545
    restart: unless-stopped
